//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalQuizProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_QUESTION
    {
        public int QUESTION_ID { get; set; }
        public string QUESTION_TXT { get; set; }
        public string OPA { get; set; }
        public string OPB { get; set; }
        public string OPC { get; set; }
        public string OPD { get; set; }
        public string COP { get; set; }
        public Nullable<int> QUESTION_FK_CAT { get; set; }
    
        public virtual TBL_CATEGORY TBL_CATEGORY { get; set; }
    }
}
